services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: flash
      POSTGRES_PASSWORD: flash
      POSTGRES_DB: flash
    volumes:
      - flash_pg:/var/lib/postgresql/data

volumes:
  flash_pg:
